
#include "storage.h"

#define STORAGE_SYS 0x01

#define STORAGE_NRL_ID 0x02
#define STORAGE_NRL_SURFACE_ID 0x01

#define STORAGE_NRL_SURFACE STORAGE_ENTRY(STORAGE_NRL_ID, STORAGE_NRL_SURFACE_ID, 1, 4*5)


